"use client";

import { useEffect, useState, type FormEvent } from "react";
import { SunMedium } from "lucide-react";

import { LoadingSpinner } from "@/components/LoadingSpinner";
import { ReadingCard } from "@/components/ReadingCard";
import { ResultPanel } from "@/components/ResultPanel";
import {
  addHistoryItem,
  createHistoryId,
  formatHistoryDate,
  readHistory,
  type ReadingHistoryItem
} from "@/lib/history";
import { compactText } from "@/lib/utils";
import type { AiResult, HoroscopeResult } from "@/types/reading";

const historyKey = "mystic-history-horoscope";

const zodiacSigns = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces"
];

export function HoroscopeClient() {
  const [sign, setSign] = useState("Aries");
  const [result, setResult] = useState<AiResult<HoroscopeResult> | null>(null);
  const [history, setHistory] = useState<ReadingHistoryItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setHistory(readHistory(historyKey));
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch("/api/readings/horoscope", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sign })
      });
      const payload = (await response.json()) as
        | AiResult<HoroscopeResult>
        | { error: string };

      if (!response.ok || "error" in payload) {
        throw new Error("error" in payload ? payload.error : "Unable to generate horoscope.");
      }

      const createdAt = new Date().toISOString();

      setResult(payload);
      setHistory(
        addHistoryItem(historyKey, {
          id: createHistoryId(),
          title: payload.data.title,
          summary: compactText(payload.data.overallEnergy, 140),
          createdAt,
          meta: `${sign} · ${formatHistoryDate(createdAt)}`
        })
      );
    } catch (caughtError) {
      setError(
        caughtError instanceof Error
          ? caughtError.message
          : "Something went wrong while generating the horoscope."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="grid gap-6 lg:grid-cols-[0.82fr_1.18fr]">
      <div className="grid gap-6">
        <ReadingCard title="Daily horoscope" description="Select a zodiac sign for a fresh reflective forecast.">
          <form className="grid gap-4" onSubmit={handleSubmit}>
            <label>
              <span className="mb-2 block text-sm font-medium text-stone-200">
                Zodiac sign
              </span>
              <select
                value={sign}
                onChange={(event) => setSign(event.target.value)}
                className="focus-ring w-full rounded-md border border-white/10 bg-black/25 px-3 py-3 text-sm text-white"
              >
                {zodiacSigns.map((zodiacSign) => (
                  <option key={zodiacSign}>{zodiacSign}</option>
                ))}
              </select>
            </label>
            <button disabled={loading} type="submit" className="button-primary disabled:cursor-not-allowed disabled:opacity-60">
              <SunMedium className="h-4 w-4" aria-hidden="true" />
              Generate Horoscope
            </button>
            <p className="text-xs leading-5 text-stone-500">
              Reflective entertainment only, including the money section. Results
              may be generated by your configured AI provider or local mock mode.
            </p>
          </form>
        </ReadingCard>

        {history.length ? (
          <ReadingCard title="Recent horoscopes">
            <ul className="space-y-3">
              {history.slice(0, 3).map((item) => (
                <li key={item.id} className="rounded-lg border border-white/10 bg-black/15 p-3">
                  <p className="text-sm font-semibold text-white">{item.title}</p>
                  {item.meta ? (
                    <p className="mt-1 text-xs text-brass">{item.meta}</p>
                  ) : null}
                  <p className="mt-1 text-xs leading-5 text-stone-400">{item.summary}</p>
                </li>
              ))}
            </ul>
          </ReadingCard>
        ) : null}
      </div>

      <div className="grid gap-4 content-start">
        {loading ? <LoadingSpinner label="Reading the sky" /> : null}
        {error ? (
          <p className="rounded-lg border border-rose-300/25 bg-rose-300/10 p-4 text-sm text-rose-100">
            {error}
          </p>
        ) : null}
        {result ? (
          <ResultPanel
            title={result.data.title}
            mode={result.mode}
            warning={result.warning}
            shareText={[
              result.data.title,
              `Overall: ${result.data.overallEnergy}`,
              `Love: ${result.data.love}`,
              `Career: ${result.data.career}`,
              `Money: ${result.data.money}`,
              `Lucky details: ${result.data.luckyColor}, ${result.data.luckyNumber}`
            ].join("\n\n")}
            sections={[
              { title: "Overall energy", content: result.data.overallEnergy },
              { title: "Love", content: result.data.love },
              { title: "Career", content: result.data.career },
              { title: "Money", content: result.data.money },
              {
                title: "Lucky details",
                content: `${result.data.luckyColor} with number ${result.data.luckyNumber}`
              }
            ]}
          />
        ) : (
          <div className="panel rounded-lg p-6 text-sm leading-6 text-stone-300">
            Aries starts by default, and every sign works in mock mode until an API key is configured.
          </div>
        )}
      </div>
    </div>
  );
}
